Repository Superalgos/Superalgos, pull requests merged in 2022-09, with the labels that each got.

#4306 Added Edge Case for Installs on Computers with only 1GB RAM
  README.md
Labels: Foundations

#4325 Added Murrey Math Lines docs
  Launch-Scripts/runPlatform.js
  Projects/Foundations/PNGs/Docs/indicators/pivots-murrey-on-the-charts.png
  Projects/Foundations/PNGs/Docs/indicators/pivots-murrey-params.png
  Projects/Foundations/Schemas/Docs-Topics/P/Pivots/Pivots-Data-Mine/pivots-data-mine-009-murrey-math-lines.json
  Projects/Network/SA/Modules/AppBootstrapingProcess.js
Labels: Education Project, Foundations

#4332 Test Report Files
  Bitcoin-Factory/Reports/Testnet-2022-09-06-19-23-00.CSV
  Bitcoin-Factory/Reports/Testnet-2022-09-07-23-37-00.CSV
  Bitcoin-Factory/Reports/Testnet-2022-09-11-03-45-00.CSV
  Bitcoin-Factory/Reports/Testnet-2022-09-14-17-57-00.CSV
Labels: Foundations

#4339 Update SocialBots.js
  Projects/Social-Bots/TS/Bot-Modules/SocialBots.js
Labels: Foundations

#4349 Governance: Adding SA Token on ETH
  Projects/Governance/UI/Globals/SaToken.js
Labels: Governance

#4359 add governance plugin to list of downloads for docker container
  Docker/download-plugins.sh
Labels: SysAdmin
